# Generated by Django 5.0.1 on 2024-02-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('meals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anecdote',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_anecdotes', to='groups.customgroup'),
        ),
        migrations.AddField(
            model_name='music',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_musics', to='groups.customgroup'),
        ),
        migrations.AlterField(
            model_name='anecdote',
            name='meal',
            field=models.ManyToManyField(blank=True, related_name='meal_anecdotes', to='meals.meal'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_comments', to='meals.dish'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='groups.customgroup'),
        ),
        migrations.AlterField(
            model_name='music',
            name='meal',
            field=models.ManyToManyField(blank=True, related_name='meal_musics', to='meals.meal'),
        ),
    ]
