# Generated by Django 5.0.1 on 2024-02-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_anecdote_group_music_group_alter_anecdote_meal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anecdote',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
