# Generated by Django 5.0.1 on 2024-02-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_invited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_invited',
            new_name='is_guest',
        ),
    ]
