# Generated by Django 4.1.3 on 2023-12-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anecdote',
            name='menu',
        ),
        migrations.AddField(
            model_name='anecdote',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='anecdotes', to='recettes.menu'),
        ),
    ]
