# Generated by Django 5.0.1 on 2024-01-22 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('recettes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.customgroup'),
            preserve_default=False,
        ),
    ]
