# Generated by Django 5.0.1 on 2024-01-26 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('recettes', '0003_menu_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='eaten_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='groups.customgroup'),
        ),
    ]
