# Generated by Django 5.0.1 on 2024-03-07 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_anecdote_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='guest_meals', to=settings.AUTH_USER_MODEL),
        ),
    ]
